### ISSUE TITLE
Migrating googlemusic fork

### ISSUE THREAD

**Issue by alexanderadam** [apnar/docker-image-logitech-media-server#2]
For instance [this one](https://github.com/huubbouma/squeezebox-googlemusic).

See also [this comment](https://github.com/squeezebox-googlemusic/squeezebox-googlemusic/issues/42#issuecomment-557934719).

What do you think?

**Comment by apnar** [comment]
I'm not actively using it at the moment, if you've tested it and it works better happy to switch over.

**Comment by alexanderadam** [comment]
Ah, nevermind. Google Music is shutting down [as huubbouma correctly pointed out](https://github.com/squeezebox-googlemusic/squeezebox-googlemusic/issues/42#issuecomment-660211803).
I did not know that.
