### ISSUE TITLE
newest version not installed

### ISSUE THREAD

**Issue by Fenix4k** [apnar/docker-image-logitech-media-server#6]
hey there

thanks for your work, works pretty awesome when installing!

Only thing that doesnt work (and I dont know why) but maybe the problem ist not with your docker image:
when I upgrade the docker image with rancher, it doesn't install the newest version. ich checked your dockerfile and they way you get the nightly and that seems to work out right

so i do not believe there's much to be done on your side ... but maybe i'm overlooking something?

**Comment by apnar** [comment]
The way the container works it only pulls the latest version when the container is built.  This use to happen every time the underlying ubuntu image was updated so was reasonably frequent but at some point Docker changed it so it wouldn't trigger from official images any more so now it tends to get a bit stale unless I remember to trigger a build.

I just triggered one now, so it should be updated in a bit here.  If you know of a better way I'm open to suggestion.

**Comment by Fenix4k** [comment]
ok, i wrote a thread in the rancher forums and asked if there's a way to force a build

i let you know if i get something, thanks for your help
